image: node:latest

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

variables:
  CHROME_BIN: /usr/bin/google-chrome
  CHROME_PATH: /usr/bin/google-chrome

before_script:
  - apt-get update
  - apt-get install -y wget gnupg
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
  - apt-get update
  - apt-get install -y google-chrome-stable
  - npm install
  - npm install webdriverio@latest
  - npm install @wdio/cli@latest
  - npm install wdio-chromedriver-service@latest
  - pwd
  - ls -la

lint:
  stage: lint
  script:
    - npm run lint
    - npm run format:check
  artifacts:
    paths:
      - .eslintrc.json
      - .prettierrc

test:
  stage: test
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - allure-results/
      - spec-reports/
    reports:
      junit: spec-reports/*.xml 